coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 5%  # the leniency in hitting the target

ignore:
  - "internal/nvm/preallocate"