name: Go

on:
  push:
    branches: ['*', '*/*']
    tags: ['v*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  test:
    name: test
    strategy:
      matrix:
        go: ["1.22.x"]
    runs-on: macos-latest
    steps:
      - name: Setup Go
        with:
          go-version: ${{ matrix.go }}
        uses: actions/setup-go@v2

      - uses: actions/checkout@v2

      - name: Test
        run: go test ./... -run=TestNode_ -count=1 -v

      # - name: Bench
      #   run: go test -run='^$' -bench BenchmarkNode_ ./... -timeout=0
